# Generated by Django 3.2.7 on 2023-04-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='preview_body',
            field=models.TextField(default='preview bodying yay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='tag',
            field=models.TextField(default='FirstPantryVisit'),
            preserve_default=False,
        ),
    ]
